// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faeshayxkjcthtgbzwdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZXNoYXl4a2pjdGh0Z2J6d2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjU3MjcsImV4cCI6MjA2ODU0MTcyN30.F1IH9XpqhVDEIcBO5ne8NRUqJ2xefs5JCVal5rj4cWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});